apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-applicaitonset
  namespace: argocd
spec:
  generators:
  # This is a git generator, reference here https://argocd-applicationset.readthedocs.io/en/stable/Generators-Git/
  - git:
      repoURL: https://github.com/jeromedecoster/my-app.git
      revision: HEAD
      directories:
      - path: git/*
      # - path: git/applicationset
      #   exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: '{{path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/jeromedecoster/my-app.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true