apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-applicaitonset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev
      - namespace: test
  template:
    metadata:
      # will generate applications with different names for example (dev-app, test-app, etc..)
      name: '{{namespace}}-app'
    spec:
      # applications will be in default project for argocd
      project: default
      source:
        repoURL: https://github.com/jeromedecoster/my-app.git
        targetRevision: HEAD
        path: argocd
      destination:
        # default cluster as destination, you can define multiple clusters in ArgoCD UI
        server: https://kubernetes.default.svc
        # will deploy to different namespaces as different destinations 
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true