apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-applicaitonset
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - env: prd
          - env: dev
      # This is a git generator, reference here https://argocd-applicationset.readthedocs.io/en/stable/Generators-Git/
      - git:
          repoURL: https://github.com/jeromedecoster/my-app.git
          revision: HEAD
          directories:
          - path: git/*
          - path: git/my-ignored-app
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
      namespace: '{{path.basename}}-{{env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/jeromedecoster/my-app.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{env}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true